### ISSUE TITLE
nzget cannot extract the files because unrar is missing

### ISSUE THREAD

**Issue by groenator** [hotio/docker-suitarr#11]
I cannot extract files because unrar is missing from the image.

ERROR | Fri May 25 2018 19:21:12 | Unrar: Could not start unrar: No such file or directory
-- | -- | --

**Comment by hotio** [comment]
Configure nzbget correctly. Unrar comes bundled with nzbget.

**Comment by groenator** [comment]
First, I wasn't expecting an answer like yours. Second, if nzbget is coming
with unrar preinstalled,  then, how come nzbget is complaining about unrar
missing from the image? If you would pay a bit of attention you will see
that the unrar binary is missing from the image.

The error I sent you is from nzbget. I used a different image and the unrar
is preinstalled as it should be.

At the end of the day only 3 lines are missing from dockerfile, not sure
why is such a hassle.

**Comment by hotio** [comment]
Not sure what response you were expecting... In most cases up until now, people put back their old configs from previous installs, likely referenced to another unrar besides the one bundled with nzbget. Therefore I ask you to configure/check your path to unrar.

But apparently you already did and so if I ask to attach to the docker instance and do `ls /app`, no `unrar` will pop up? If so we'll have to investigate why it fails to properly install on your instance.

What 3 lines are missing?

Not trying to get in a fight here, but what's the resaon for your rude response and the need to tell me I have a problem paying attention?

**Comment by groenator** [comment]
All I am trying to say is, add the unrar package in the docker file. This
way unrar would be installed and nzbget won't complain. I've checked the
binary and is not inside the container. The only binary that you can use
for extracting files is unzip, which you already add it into the docker
file.

I will do an ls on /app, but I doubt it is there, ideally it should be in
the /usr/bin.

I am not trying to be rude.

The reason I said 3 lines it's because unrar is installed from a different
repo. You won't find it in the official Ubuntu repos. The package is locate
in the multiverse repo.

I can clone your repo, modify dockerfile and push it back, as long you can
merge my pull into your master branch.

Regards,

**Comment by hotio** [comment]
I will not pull those changes, no point in adding unrar twice. Unrar is available and works for me and hundreds of other people...

**Comment by hotio** [comment]
Still waiting here for the output of `ls /app`.

**Comment by groenator** [comment]
unrar is in /app - maybe would be best to tell in your documentation that unrar is in /app -

**Comment by hotio** [comment]
Every nzbget user is supposed to know this, every clean install of nzbget has unrar bundled and the path set to `${AppDir}/unrar`. I'm not doing anything out of the ordinary, so if nzbget fails to unrar, the user messed up (if so, they should be able to undo their mistake), if it wasn't the user, something else messed it up.

I shouldn't be documenting for others screwing up the defaults. A cleanly created container, without any previous configs, is supposed to work. If it doesn't that's on me, if the user messes up their config that's on them.

Please keep in mind that this is GitHub-Issues, not a user support forum. That's why you'll see a lot of issues being ignored on other projects. I personally prefer to give a fast/short reply to get the user going in the right direction while simultaneous close any non-issue.

So can we assume there's nothing wrong with my attention span?
